import re

with open('D:/SophiaAgentWork/SophiaAgent/sophia/cli.py', 'r', encoding='utf-8') as f:
    cli_content = f.read()

init_code = """
def cmd_init(args):
    \"\"\"Interactive setup wizard for SophiaAgent.\"\"\"
    import yaml
    from pathlib import Path
    
    console = Console()
    console.print(Panel.fit(
        "[bold color(214)]SophiaAgent Setup Wizard[/]",
        border_style="color(214)"
    ))
    
    # Provider selection
    provider_choices = ["openai-compat", "anthropic", "openai"]
    console.print("\n[bold]1. Select LLM Provider:[/]")
    for i, p in enumerate(provider_choices):
        console.print(f"  [cyan]{i+1}[/]. {p}")
    provider_idx = input(f"Enter choice (1-{len(provider_choices)}) [1]: ").strip()
    try:
        p_idx = int(provider_idx) - 1
        if not (0 <= p_idx < len(provider_choices)):
            p_idx = 0
    except ValueError:
        p_idx = 0
    provider = provider_choices[p_idx]
    
    # Base URL (for openai-compat)
    base_url = ""
    if provider == "openai-compat":
        console.print("\n[bold]2. API Base URL (e.g. https://api.deepseek.com/v1):[/]")
        base_url = input("> ").strip()
    
    # API Key
    console.print(f"\n[bold]3. API Key for {provider}:[/]")
    api_key = input("> ").strip()
    
    # Model Name
    console.print("\n[bold]4. Model Name (e.g. deepseek-chat, gpt-4o, claude-3-5-sonnet-20241022):[/]")
    model_name = input("> ").strip()
    
    # Workspace
    default_ws = str(Path.home() / "SophiaWorkspace")
    console.print(f"\n[bold]5. Workspace Directory (default: {default_ws}):[/]")
    workspace = input("> ").strip()
    if not workspace:
        workspace = default_ws
        
    # Semantic Scholar
    console.print("\n[bold]6. Semantic Scholar API Key (optional, press Enter to skip):[/]")
    scholar_key = input("> ").strip()
    
    # Save config
    config = Config.create_default()
    config.model.provider = provider
    config.model.base_url = base_url
    config.model.api_key = api_key
    config.model.name = model_name
    config.session.workspace = workspace
    
    config_dir = Path.home() / ".sophia-agent"
    config_dir.mkdir(parents=True, exist_ok=True)
    config_path = config_dir / "config.yaml"
    
    # We update the dumped config
    config_dict = config.to_dict()
    if scholar_key:
        # Assuming you may want to put keys in config if supported or just env
        pass
        
    with open(config_path, "w", encoding="utf-8") as f:
        yaml.dump(config_dict, f, default_flow_style=False, allow_unicode=True)
        
    # Write to local .env in the cwd
    env_path = Path(".env")
    env_lines = [
        "# Auto-generated by sophia init"
    ]
    if provider == "openai":
        env_lines.append(f"OPENAI_API_KEY={api_key}")
        env_lines.append(f"SOPHIA_MODEL={model_name}")
    elif provider == "anthropic":
        env_lines.append(f"ANTHROPIC_API_KEY={api_key}")
        env_lines.append(f"SOPHIA_MODEL={model_name}")
    else:
        env_lines.append(f"SOPHIA_BASE_URL={base_url}")
        env_lines.append(f"SOPHIA_API_KEY={api_key}")
        env_lines.append(f"SOPHIA_MODEL={model_name}")
        
    if scholar_key:
        env_lines.append(f"SEMANTIC_SCHOLAR_API_KEY={scholar_key}")
        
    with open(env_path, "w", encoding="utf-8") as f:
        f.write("\n".join(env_lines) + "\n")
        
    console.print("\n[bold color(107)]✓ Configuration successful![/]")
    console.print(f"  Configuration saved to: [dim]{config_path}[/]")
    console.print(f"  Environment variables saved to: [dim]{env_path.absolute()}[/]")
    
"""

cmd_doctor_idx = cli_content.find("def cmd_doctor(args):")
cli_content = cli_content[:cmd_doctor_idx] + init_code + "\n" + cli_content[cmd_doctor_idx:]

parser_idx = cli_content.find("p_doctor = subparsers.add_parser(")
parser_code = """
    p_init = subparsers.add_parser("init", help="Interactive setup wizard")
    p_init.set_defaults(func=cmd_init)

    p_doctor = subparsers.add_parser(
"""
cli_content = cli_content.replace('    p_doctor = subparsers.add_parser(', parser_code.strip() + '(', 1)

with open('D:/SophiaAgentWork/SophiaAgent/sophia/cli.py', 'w', encoding='utf-8') as f:
    f.write(cli_content)
