from sophia.task_harness import (
    build_task_harness_prompt,
    is_complex_task,
    is_empirical_request,
    may_need_skill,
)


def test_empirical_request_detection_covers_chinese_and_english():
    assert is_empirical_request("做一个实证回归和稳健性检验")
    assert is_empirical_request("run causal regression with robustness checks")


def test_complex_task_detection_includes_research_and_empirical():
    assert is_complex_task("写一篇完整论文")
    assert is_complex_task("estimate DID with panel data")


def test_skill_detection_for_reusable_workflows():
    assert may_need_skill("把这个固定流程做成可复用技能")
    assert may_need_skill("reuse this workflow as a template")


def test_harness_prompt_requires_plan_tools_and_quality_loop():
    prompt = build_task_harness_prompt("写一篇完整研究报告", workspace_has_evidence=True)

    assert "Mandatory execution loop" in prompt
    assert "Make a detailed step-by-step plan" in prompt
    assert "Use `goal_create`" in prompt
    assert "Use `skill_list`" in prompt
    assert "evidence ledger" in prompt
    assert "Workspace policy" in prompt


def test_empirical_harness_requires_execution_and_credibility_checks():
    prompt = build_task_harness_prompt(
        "做实证回归和可信性检验",
        empirical_preflight='{"ready_to_run": false}',
    )

    assert "Empirical execution contract" in prompt
    assert "empirical_workflow_plan" in prompt
    assert "empirical_workflow_run" in prompt
    assert "Credibility checks are mandatory" in prompt
    assert "Do not invent a sample" in prompt
    assert "[Empirical preflight plan generated by Sophia]" in prompt
